from datetime import datetime
from typing import Any

class V1ObjectMeta:
    name: str = ...
    namespace: str = ...
    def __init__(
        self, name: str | None = None, namespace: str | None = None, **kwargs: Any
    ) -> None: ...

class V1ContainerStateWaiting:
    message: str = ...
    reason: str = ...
    def __init__(
        self, message: str | None = None, reason: str | None = None, **kwargs: Any
    ) -> None: ...

class V1ContainerState:
    running: dict[str, Any] | None = ...
    terminated: dict[str, Any] | None = ...
    waiting: V1ContainerStateWaiting | None = ...
    def __init__(self, **kwargs: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class V1ContainerStatus:
    container_id: str = ...
    image: str = ...
    image_id: str = ...
    last_state: V1ContainerState | None = ...
    name: str = ...
    ready: bool = ...
    restart_count: int = ...
    started: bool = ...
    state: V1ContainerState | None = ...
    def __init__(self, **kwargs: Any) -> None: ...

class V1PodCondition:
    last_probe_time: datetime | None = ...
    last_transition_time: datetime | None = ...
    message: str = ...
    reason: str = ...
    status: str = ...
    type: str = ...
    def __init__(self, **kwargs: Any) -> None: ...

class V1PodStatus:
    conditions: list[V1PodCondition] = ...
    container_statuses: list[V1ContainerStatus] = ...
    ephemeral_container_statuses: list[V1ContainerStatus] | None = ...
    host_ip: str = ...
    init_container_statuses: list[V1ContainerStatus] | None = ...
    message: str = ...
    nominated_node_name: str = ...
    phase: str = ...
    pod_ip: str = ...
    pod_ips: list[dict[str, Any]] | None = ...
    qos_class: str = ...
    reason: str = ...
    start_time: datetime | None = ...
    def __init__(self, **kwargs: Any) -> None: ...

class V1PodSpec:
    node_name: str = ...
    def __init__(self, **kwargs: Any) -> None: ...

class V1Pod:
    metadata: V1ObjectMeta = ...
    spec: V1PodSpec = ...
    status: V1PodStatus = ...
    def __init__(self, **kwargs: Any) -> None: ...

class V1PodList:
    items: list[V1Pod] = ...
    def __init__(self, **kwargs: Any) -> None: ...

class CoreV1Event:
    action: str = ...
    api_version: str = ...
    count: int = ...
    event_time: datetime | None = ...
    first_timestamp: datetime | None = ...
    involved_object: V1ObjectMeta | None = ...
    kind: str = ...
    last_timestamp: datetime | None = ...
    message: str = ...
    metadata: V1ObjectMeta = ...
    reason: str = ...
    related: V1ObjectMeta | None = ...
    reporting_component: str = ...
    reporting_instance: str = ...
    series: Any | None = ...
    source: Any | None = ...
    type: str = ...
    def __init__(self, **kwargs: Any) -> None: ...

class CoreV1EventList:
    items: list[CoreV1Event] = ...
    api_version: str = ...
    kind: str = ...
    metadata: V1ObjectMeta | None = ...
    def __init__(self, **kwargs: Any) -> None: ...
